prefix               = "stg"
resource_group_name  = "rg-staging"
location             = "westeurope"
storage_account_name = "tfwebstorage4123"
index_document       = "index.html"
index_404_document   = "404.html"
